theme: jekyll-theme-minimal
title: [Sampanna Sharma]
description: [A short description of your site's purpose]
logo: [https://github.com/Sampanna-Sharma/Sampanna-Sharma.github.io/tree/master/misc/logo.jpeg]
